PREFIX togaf: <http://www.semanticweb.org/ontologies/2010/0/OntologyTOGAFContentMetamodel.owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?component ?label ?description ?kind
WHERE {
  ?component rdfs:label ?label .
  OPTIONAL { ?component rdfs:comment ?description } .
  ?component rdf:type ?kind
  { ?component a togaf:BusinessService } UNION { ?component a togaf:Function } UNION { ?component a togaf:InformationSystemService } .
}
