PREFIX togaf: <http://www.semanticweb.org/ontologies/2010/0/OntologyTOGAFContentMetamodel.owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?component ?label ?description ?kind
WHERE {
  GRAPH ?g1 { ?component rdfs:label ?label } .
  OPTIONAL { GRAPH ?g2 { ?component rdfs:comment ?description } } .
  GRAPH ?g3 { ?component rdf:type ?kind } .
  GRAPH ?g4 { ?component a ?class } .
  GRAPH ?t { ?class rdfs:subClassOf togaf:BusinessArchitectureComponent } .
}
