PREFIX togaf: <http://www.semanticweb.org/ontologies/2010/0/OntologyTOGAFContentMetamodel.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?from ?label ?to
WHERE {
  ?from ?label ?to .
  ?from a ?class1 .
  ?class1 rdfs:subClassOf togaf:BusinessArchitectureComponent .
  ?to a ?class2 .
  ?class2 rdfs:subClassOf togaf:BusinessArchitectureComponent .
}
