PREFIX togaf: <http://www.semanticweb.org/ontologies/2010/0/OntologyTOGAFContentMetamodel.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?from ?label ?to
WHERE {
  GRAPH ?g1 { ?from ?label ?to } .
  GRAPH ?g2 { ?from a ?class1 } .
  GRAPH ?g3 { ?to a ?class2 } .
  GRAPH ?t1 { ?class1 rdfs:subClassOf togaf:BusinessArchitectureComponent } .
  GRAPH ?t2 { ?class2 rdfs:subClassOf togaf:BusinessArchitectureComponent } .
}
