PREFIX togaf: <http://www.semanticweb.org/ontologies/2010/0/OntologyTOGAFContentMetamodel.owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?label ?type ?description
WHERE {
  ?subject rdfs:label ?label .
  OPTIONAL { ?subject rdfs:comment ?description } .
  ?subject rdf:type ?type
  { ?subject a togaf:BusinessService } UNION { ?subject a togaf:Function } UNION { ?subject a togaf:InformationSystemService } .
}
